### ISSUE TITLE
<Web : forward button> working on 

### ISSUE THREAD

**Issue by KKimj** [jonataslaw/getx#1433]
## ```Back button``` is good, but ```Forward button``` is not activated 

Hello, thanks your effort for GetX!!

I want to return to page, but forward button is not activated

![ezgif com-gif-maker](https://user-images.githubusercontent.com/40026920/118363660-5c390d80-b5d0-11eb-80c3-d7ad328893e8.gif)

![image](https://user-images.githubusercontent.com/40026920/118363508-a40b6500-b5cf-11eb-8255-4ac5a28a082b.png)

![image](https://user-images.githubusercontent.com/40026920/118363517-b8e7f880-b5cf-11eb-8336-1d6cea87f458.png)

---

This is code blocks 
```dart
class MainScaffold extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var _getPages = <GetPage>[
      GetPage(name: '/', page: () => MainPage()),
      GetPage(name: '/sub', page: () => SubPage()),
      GetPage(name: '/react', page: () => ReactivePage()),
    ];

    return GetMaterialApp(
      title: 'Flutter template',
      home: MainPage(),
      theme: null,
      getPages: _getPages,
      initialBinding: AppBinding(),
    );
  }
}
```

```dart
class MainPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    AppModelViewmodel.to.title_update(title: 'Flutter template');
    return Scaffold(
      appBar: AppBar(),
      body: SafeArea(child: ResponsiveBuilder(
        builder: (context, sizingInformation) {
          return Center(
            child: Column(
              children: [
                Text('Hello template'),
                ElevatedButton(
                  onPressed: () {
                    Get.toNamed('/sub');
                  },
                  child: Text('Go to subpage!'),
                ),
                ElevatedButton(
                  onPressed: () {
                    Get.toNamed('/react');
                  },
                  child: Text('Go to reactive page!'),
                ),
                GetBuilder<TestViewmodel>(builder: (_) {
                  return ElevatedButton(
                    onPressed: () {
                      var id = TestViewmodel.to.test.id + 1;
                      var value = TestViewmodel.to.test.value + 1;
                      TestViewmodel.to.test_update(id: id, value: value);
                    },
                    child: Text('update !'
                        '${TestViewmodel.to.test.id} / ${TestViewmodel.to.test.value}'),
                  );
                }),
              ],
            ),
          );
        },
      )),
    );
  }
}
```

```dart

class AppModelViewmodel extends GetxController {
  var appModel = AppModel(title: 'flutter template');

  void title_update({required String title}) {
    appModel = AppModel(title: title);

    SystemChrome.setApplicationSwitcherDescription(
        ApplicationSwitcherDescription(
      label: appModel.title,
      primaryColor: 0x0,
    ));
    update();
  }

  static AppModelViewmodel get to => Get.find();

  String get title => appModel.title;
}

```

**Flutter Version & Getx Version:**

```yaml

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  get: ^4.1.4
  pedantic: ^1.11.0
  freezed_annotation:
  responsive_framework: ^0.1.0
  responsive_builder: ^0.4.1
```

**Describe on which device you found the bug:**
Chrome

Thanks!
