### ISSUE TITLE
  Get.changeTheme（）not work in iPhone7 with IOS14.7.1

### ISSUE THREAD

**Issue by SinoMiles** [jonataslaw/getx#1827]
**Describe the bug**
changeTheme() not work in iPhone 7 .my iPhone 12 (14.6) and iPhone x (14.7.1) works fine.

example:

```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
                onPressed: () {
                  Get.changeTheme(ThemeData(
                      appBarTheme: AppBarTheme(backgroundColor: Colors.black)));
                },
                child: Text('black')),
            ElevatedButton(
                onPressed: () {
                  Get.changeTheme(ThemeData(
                      appBarTheme: AppBarTheme(
                    backgroundColor: Colors.white,
                  )));
                },
                child: Text('white'))
          ],
        ),
      ),
    );
  }
}

```
```
name: flutter_application_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
**To Reproduce**
1.click button to change theme
2.not work

**Screenshots**
iPhone 7 iOS 14.7.1

https://user-images.githubusercontent.com/9588025/131778785-3b852c31-54b9-432f-9dc9-97ee8ea9ee74.mp4

iPhone12 pro Max simulator  works fine
![simulator_screenshot_C1E38BE9-4E80-4A57-A6F1-6EDA4809C013](https://user-images.githubusercontent.com/9588025/131778853-8a2663c9-fce0-4891-a983-aeb59b081e87.png)
![simulator_screenshot_EF10C2FC-72F7-4BF8-A726-C8438351EF2D](https://user-images.githubusercontent.com/9588025/131778857-5fd0f891-7f89-4d48-a839-5a9ab5d61532.png)

**Flutter Version:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.1 20D75 darwin-x64, locale
    en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.59.1)
[✓] Connected device (3 available)

**Getx Version:**
  get: ^4.3.8

**Describe on which device you found the bug:**
ex: IPhone7
