### ISSUE TITLE
[Error] Cannot parse json with nested structure

### ISSUE THREAD

**Issue by huubao2309** [jonataslaw/getx#2199]
- I'm using `get: ^4.6.1` for my app (Android and iOS).  I have an error when I get json string, which the server response.
- Server Response (I use postman):
```yaml
{
  "results": [
    {
      "chat": {
        "lastMessage": {
          "content": "https://www.w3schools.com/howto/img_avatar.png",
          "type": "IMAGE"
        },
        "profile": {
          "photoUrl": "https://www.w3schools.com/howto/img_avatar.png",
          "fullName": "Tom"
        }
      }
    },
    {
      "chat": {
        "lastMessage": {
          "content": "Hello",
          "type": "TEXT"
        },
        "profile": {
          "photoUrl": "",
          "fullName": "Jerry"
        }
      }
    },
	{
      "chat": {
        "lastMessage": {
          "content": "How are you",
          "type": "TEXT"
        },
        "profile": {
          "photoUrl": "",
          "fullName": ""
        }
      }
    }
  ]
}
```
- But when I call from API GET of GetConnect. 
- Response:
```yaml
{
  "results": [
    {
      "chat": {
        "lastMessage": {
          "content": "https://www.w3schools.com/howto/img_avatar.png",
          "type": "IMAGE"
        },
        "profile": null
      }
    },
    {
      "chat": {
        "lastMessage": {
          "content": "Hello",
          "type": "TEXT"
        },
        "profile": {
          "photoUrl": "",
          "fullName": "Jerry"
        }
      }
    },
    {
      "chat": {
        "lastMessage": {
          "content": "How are you",
          "type": "TEXT"
        },
        "profile": null
      }
    }
  ]
}
```
