### ISSUE TITLE
Double dependency injection while using Getx alongside audio_service in Android (flutter 3)

### ISSUE THREAD

**Issue by christiancg** [jonataslaw/getx#2369]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
Seems that using flutter 3 (stable channel), while on Android, if you use getx (latest version -> 4.6.3) alongside audio_service (latest version -> 0.18.4), when you make Get.put() or Get.lazyPut() of any service, you will see in the console that the service is created and initialized twice. This is only happening for Android, it is working correctly in iOS. This causes errors while instantiating some services that need only one instance. In my case, it is causing errors with the local database (Objectbox).

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
import 'package:get/get_state_manager/get_state_manager.dart';
import 'package:get/instance_manager.dart';

void main() {
  Get.put(FakeService());
}

class FakeService extends GetxService {
}
```

```yaml
name: getx_error
description: Showing how to reproduce interaction error between getx and audio_service
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.3
  audio_service: ^0.18.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
```

**To Reproduce**
Run the code above on any Android device (won't happen in any iOS device)

**Expected behavior**
Only one instance of each service should be created and initialized

**Screenshots**
<img width="552" alt="image" src="https://user-images.githubusercontent.com/8180797/169043901-c487739f-cbd6-4802-b55d-c27310935562.png">

**Flutter Version:**
Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (9 days ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

**Getx Version:**
4.6.3

**Describe on which device you found the bug:**
Any android device

**Minimal reproduce code**
Provide a minimum reproduction code for the problem
(with getx 4.6.3 and audio_service 0.18.4 installed)

```dart
import 'package:get/get_state_manager/get_state_manager.dart';
import 'package:get/instance_manager.dart';

void main() {
  Get.put(FakeService());
}

class FakeService extends GetxService {
}
```
