### ISSUE TITLE
getx GetConnect onInit not work

### ISSUE THREAD

**Issue by giantss** [jonataslaw/getx#2540]
getx GetConnect onInit not working causing this error. `Unhandled Exception: Invalid argument(s): No host specified in URI albums/1`

Here is a simple example
 https://github.com/giantss/flutterGetxTest/tree/main/testapp

example:

```
import 'package:get/get.dart';
import '../home_model.dart';

class HomeProvider extends GetConnect {
  @override
  void onInit() {    // no call
    httpClient.defaultDecoder = (map) {
      if (map is Map<String, dynamic>) return Home.fromJson(map);
      if (map is List) return map.map((item) => Home.fromJson(item)).toList();
    };
    httpClient.baseUrl = 'https://jsonplaceholder.typicode.com/';   
  }

  Future<Home?> getHome(int id) async {
    final response = await get('albums/$id');  // error is thrown here
    return response.body;
  }

  Future<Response<Home>> postHome(Home home) async => await post('home', home);
  Future<Response> deleteHome(int id) async => await delete('home/$id');
}
```

 `pubspec.yaml`

```
name: testapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


```
