### ISSUE TITLE
WidgetTester Example in Example App

### ISSUE THREAD

**Issue by ghenry** [jonataslaw/getx#418]
**Is your feature request related to a problem? Please describe.**
I'm doing this in my own app like the stock test in a new Flutter project:
```
import 'package:flutter_test/flutter_test.dart';
import 'package:SureVoIPTalk/src/app.dart';

void main() {
  testWidgets('Check login page shows', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(SureVoIPTalkApp());

    // Verify that our counter starts at 0.
    //expect(find.text('Email'), findsOneWidget);
    expect(find.text('Next'), findsWidgets);

//    // Tap the '+' icon and trigger a frame.
//    await tester.tap(find.text('Next'));
//    await tester.pump();
//
//    // Verify that our error is shown.
//    expect(find.text('Please enter a valid email'), findsOneWidget);
  });
}
```
and get:

```
flutter test test/widget_login_test.dart 
00:02 +0: Check login page shows                                                                                                                                                                                       
[GET] GetMaterialController has been initialized
Loading isLoggedIn as "false" from device.
Loaded fullname from device as: null
Loaded email from device as: null
[GET] AuthController has been initialized
[GOING TO ROUTE] /
[GOING TO ROUTE] /LoginScreen
[REMOVING ROUTE] /
[GOING TO ROUTE] /LoginScreen
[REMOVING ROUTE] /LoginScreen
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: at least one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "Next" (ignoring offstage widgets)>
   Which: means none were found but some were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/ghenry/AndroidStudioProjects/SureVoIP-Talk/test/widget_login_test.dart:19:5)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///home/ghenry/AndroidStudioProjects/SureVoIP-Talk/test/widget_login_test.dart)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:140:29)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:703:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:683:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1083:24)
#18     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1080:15)
#19     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:133:24)
#20     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
<asynchronous suspension>
#21     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#22     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
#27     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
#28     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
#33     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#34     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:30)
(elided 31 frames from class _FakeAsync, class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/ghenry/AndroidStudioProjects/SureVoIP-Talk/test/widget_login_test.dart line 19
The test description was:
  Check login page shows
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +0 -1: Check login page shows [E]                                                                                                                                                                                
  Test failed. See exception logs above.
  The test description was: Check login page shows
  
00:03 +0 -1: loading /home/ghenry/AndroidStudioProjects/SureVoIP-Talk/test/widget_login_test.dart                                                                                                                      
Warning: At least one test in this suite creates an HttpClient. When
running a test suite that uses TestWidgetsFlutterBinding, all HTTP
requests will return status code 400, and no network request will
actually be made. Any test expecting a real network connection and
status code will fail.
To test code that needs an HttpClient, provide your own HttpClient
implementation to the code under test, so that your test can
consistently provide a testable response to the code under test.
00:03 +0 -1: Some tests failed.                                          
```

**Describe the solution you'd like**
I'd like the Example has to have one or a few tests to reference.

**Describe alternatives you've considered**
I'll look at a PR myself later this week too.

Thanks.

**Comment by ghenry** [comment]
I'm not actually testing a Widget here, but loading the whole app, so I don't think this is right as per https://flutter.dev/docs/cookbook/testing/widget/introduction

You can ignore my errors, but it would be good to see loading up the whole example app you have here.

**Comment by ghenry** [comment]
Well, yes I am:

`class SureVoIPTalkApp extends StatelessWidget {`

so an example would be great for your example app.

**Comment by ghenry** [comment]
I was looking to add a load of tests to the example app in the getx repo, but looking for advice of how to load a GetMaterialApp:

```
import 'package:flutter_test/flutter_test.dart';
import 'package:get_state/home/views/home_view.dart';

void main() {
  testWidgets('Load our whole app and check some text',
      (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(HomePage());
    expect(find.text('Total Confirmed'), findsOneWidget);
  });
}
```

gives:

```
00:01 +0: Load our whole app and check some text                                                                                                                                                     
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Container(bg: BoxDecoration(color: Color(0xffffffff),
image:
DecorationImage(NetworkImage("https://images.pexels.com/photos/3902882/pexels-photo-3902882.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
scale: 1.0), ColorFilter.linearToSrgbGamma(), BoxFit.cover, center, scale: 1.0))):
MediaQuery.of() called with a context that does not contain a MediaQuery.
No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
The context used was:
  Scaffold

The relevant error-causing widget was:
  Container file:///home-storage/ghenry/src/getx/example/lib/home/views/home_view.dart:9:12

When the exception was thrown, this was the stack:
#0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:819:5)
#1      ScaffoldState.didChangeDependencies (package:flutter/src/material/scaffold.dart:2166:50)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4705:12)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...     Normal element mounting (16 frames)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3255:20)
#21     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1174:16)
#22     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1152:5)
#23     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1166:7)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#25     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#26     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1056:18)
#27     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#28     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#29     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#30     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:929:9)
#33     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#34     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:916:27)
#35     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:462:22)
#38     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#39     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:459:27)
#40     main.<anonymous closure> (file:///home-storage/ghenry/src/getx/example/test/widget_test.dart:8:18)
#41     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
#42     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#43     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:752:19)
<asynchronous suspension>
#46     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:732:14)
#47     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1133:24)
#48     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:177:54)
#53     withClock (package:clock/src/default.dart:46:10)
#54     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:177:22)
#59     FakeAsync.run (package:fake_async/fake_async.dart:177:7)
#60     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1130:15)
#61     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:137:24)
#62     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:19)
<asynchronous suspension>
#63     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#68     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#69     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:235:15)
#74     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:232:5)
#75     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:388:17)
<asynchronous suspension>
#76     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#81     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:374:9)
#82     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:420:15)
#83     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:373:7)
#90     Invoker._onRun (package:test_api/src/backend/invoker.dart:372:11)
#91     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:152:11)
#92     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:259:16)
#97     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:258:5)
#98     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:211:7)
#116    _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:124:12)
#117    new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#151    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#159    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#160    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#170    _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#179    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#180    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
(elided 112 frames from dart:async and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "Total Confirmed" (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home-storage/ghenry/src/getx/example/test/widget_test.dart:9:5)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///home-storage/ghenry/src/getx/example/test/widget_test.dart)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:752:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:732:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1133:24)
#13     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:177:54)
#18     withClock (package:clock/src/default.dart:46:10)
#19     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:177:22)
#24     FakeAsync.run (package:fake_async/fake_async.dart:177:7)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1130:15)
#26     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:137:24)
#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:19)
<asynchronous suspension>
#28     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#33     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#34     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:235:15)
#39     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:232:5)
#40     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:388:17)
<asynchronous suspension>
#41     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#46     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:374:9)
#47     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:420:15)
#48     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:373:7)
#55     Invoker._onRun (package:test_api/src/backend/invoker.dart:372:11)
#56     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:152:11)
#57     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:259:16)
#62     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:258:5)
#63     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:211:7)
#81     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:124:12)
#82     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#116    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#124    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#125    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#135    _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#144    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#145    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
(elided 108 frames from dart:async and package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home-storage/ghenry/src/getx/example/test/widget_test.dart line 9
The test description was:
  Load our whole app and check some text
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
00:01 +0 -1: Load our whole app and check some text [E]                                                                                                                                              
  Test failed. See exception logs above.
  The test description was: Load our whole app and check some text

```
