### ISSUE TITLE
No named parameter with the name 'shadowThemeOnly' at 1.24.0-10.2 sdk beta version

### ISSUE THREAD

**Issue by tazik561** [jonataslaw/getx#863]
I have a flutter pwa project that is works fine with `1.23.0-18.1.pre` sdk version. Now i upgraded sdk to `1.24.0-10.2.pre` :
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
```
Now i can't run my project:

```
[+9019 ms]
../../../../../Software/Linux/Flutter/flutter/.pub-cache/git/persianDatePicker-b20d15502d6cae5c5bc9b4219789e16b15debb26/lib/widget/dialo
                    g.dart:725:45: Error: No named parameter with the name 'shadowThemeOnly'.
[        ]   final ThemeData theme = Theme.of(context, shadowThemeOnly: true);
[        ]                                             ^^^^^^^^^^^^^^^
[        ] ../../../../../Software/Linux/Flutter/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this
candidate, but
           the arguments don't match.
[        ]   static ThemeData of(BuildContext context) {
[        ]                    ^^
[+1781 ms] lib/widget/date_picker/widget/dialog.dart:725:45: Error: No named parameter with the name 'shadowThemeOnly'.
[        ]   final ThemeData theme = Theme.of(context, shadowThemeOnly: true);
[        ]                                             ^^^^^^^^^^^^^^^
[        ] ../../../../../Software/Linux/Flutter/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this
candidate, but
           the arguments don't match.
[        ]   static ThemeData of(BuildContext context) {
[        ]                    ^^
[+23071 ms] Syncing files to device Chrome... (completed in 36.4s)
[        ] Synced 0.0MB.
[        ] Failed to compile application.
[   +2 ms] "flutter run" took 43,951ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:617:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1080:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:931:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```
• No issues found!

This is my pubspec.yaml:
```
dependency_overrides:
  analyzer: 0.40.4
  build_resolvers: '1.4.1'

dependencies:
  flutter:
    sdk: flutter
  persian_datetime_picker:
    git:
      url: https://gitlab.com/mortezabagheridev/persianDatePicker.git
  after_layout: ^1.0.7+2
  barcode_scan: ^1.0.0
  carousel_slider: ^2.2.1
  charts_flutter: ^0.9.0
  crypto: ^2.1.4
  cryptography: ^1.4.1
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  dotted_border: ^1.0.6
  encrypt: ^4.0.2
  esys_flutter_share: ^1.0.2
  file_picker: ^2.0.0
  firebase_messaging: ^7.0.0
  flushbar: ^1.5.0
  flutter_rating_bar: ^3.0.1+1
  flutter_redux: ^0.6.0
  flutter_slidable: ^0.5.5
  flutter_svg: ^0.18.0
  fluttertoast: ^6.0.0
  font_awesome_flutter: ^8.8.1
  generic_json_converter_generator: ^0.0.4
  geolocator: ^6.1.0
  get_it: ^4.0.4
  get_version: 0.2.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  http: ^0.12.2
  image_cropper: ^1.3.1
  image_gallery_saver: ^1.6.5
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  json_annotation: 3.1.0
  local_auth: ^0.6.3+2
  logger: ^0.9.2
  mask_text_input_formatter: ^1.1.0
  otp: ^2.2.3
  overlay_support: ^1.0.5
  page_view_indicators: ^1.3.1
  path_provider: ^1.6.11
  permission_handler: ^5.0.1+1
  persian: ^0.1.4
  persian_number_utility: ^0.1.0
  provider: ^4.3.1
  quick_actions: ^0.4.0+8
  retrofit: ^1.3.4
  rxdart: ^0.24.1
  screenshot: ^0.2.0
  search_widget: ^1.0.2
  shamsi_date: ^0.8.1
  shared_preferences: ^0.5.8
  smooth_star_rating: 1.1.1
  sqflite: ^1.3.1
  timezone: ^0.5.7
  url_launcher: ^5.5.2
  uuid: ^2.2.2
  video_player: ^0.11.0
  visibility_detector: ^0.1.5
  wc_flutter_share: ^0.2.2
  webview_flutter: ^1.0.7
dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: 1.10.3
  hive_generator: ^0.8.1
  json_serializable: ^3.5.0
  retrofit_generator: ^1.4.0+1
```
